/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4StiD2IwQ1z
 */
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"

export function Explore_1_4() {
  return (
    <div className="bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="pt-12 pb-16">
          <h2 className="text-3xl font-extrabold tracking-tight text-gray-900">Lastest News and Resources</h2>
          <p className="mt-4 max-w-2xl text-xl text-gray-500">
            See the developments that have occurred to TDTC in the world
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
          <Card className="w-full">
            <img
              alt="News image"
              className="h-48 w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <div className="p-4">
              <span className="inline-block bg-blue-100 text-blue-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                News
              </span>
              <h3 className="mt-4 text-lg font-semibold text-gray-900">
                Class adds $30 million to its balance sheet for a Zoom-friendly edtech solution
              </h3>
              <p className="mt-2 text-sm text-gray-600">
                Class, launched less than a year ago by Blackboard co-founder Michael Chasen, integrates exclusively...
              </p>
              <Button className="mt-4" variant="outline">
                Read more
              </Button>
            </div>
          </Card>
          <Card className="w-full">
            <img
              alt="Press release image"
              className="h-48 w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <div className="p-4">
              <span className="inline-block bg-green-100 text-green-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                Press Release
              </span>
              <h3 className="mt-4 text-lg font-semibold text-gray-900">
                Class Technologies Inc. Closes $30 Million Series A Financing to Meet High Demand
              </h3>
              <p className="mt-2 text-sm text-gray-600">Class Technologies Inc., the company that created Class...</p>
              <Button className="mt-4" variant="outline">
                Read more
              </Button>
            </div>
          </Card>
          <Card className="w-full">
            <img
              alt="News image"
              className="h-48 w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <div className="p-4">
              <span className="inline-block bg-blue-100 text-blue-800 text-xs px-2 rounded-full uppercase font-semibold tracking-wide">
                News
              </span>
              <h3 className="mt-4 text-lg font-semibold text-gray-900">
                Zoom`s earliest investors are betting millions on a better Zoom for schools
              </h3>
              <p className="mt-2 text-sm text-gray-600">
                Zoom was never created to be a consumer product. Nonetheless, the...
              </p>
              <Button className="mt-4" variant="outline">
                Read more
              </Button>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}
