/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/G6k2JAjg4Ri
 */
import { Avatar } from "@/components/ui/avatar"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Explore_1_2() {
  return (
    <div className="bg-gray-100">
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="bg-white p-4">
            <Avatar>
              <img
                alt="Online Billing Icon"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
            </Avatar>
            <h3 className="mt-4 text-lg font-semibold">Online Billing, Invoicing, & Contracts</h3>
            <p className="mt-2 text-sm text-gray-600">
              Simple and secure control of your organization`s financial and legal transactions. Send customized
              invoices and contracts.
            </p>
          </Card>
          <Card className="bg-white p-4">
            <Avatar>
              <img
                alt="Easy Scheduling Icon"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
            </Avatar>
            <h3 className="mt-4 text-lg font-semibold">Easy Scheduling & Attendance Tracking</h3>
            <p className="mt-2 text-sm text-gray-600">
              Effortless and accurate overview of your daily schedule of classes and attendance.
            </p>
          </Card>
          <Card className="bg-white p-4">
            <Avatar>
              <img
                alt="Customer Tracking Icon"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
            </Avatar>
            <h3 className="mt-4 text-lg font-semibold">Customer Tracking</h3>
            <p className="mt-2 text-sm text-gray-600">
              Automated tools keep track of your clients` progress. Simplify your organization`s registration and
              billing.
            </p>
          </Card>
        </div>
        <div className="my-12">
          <h2 className="text-center text-2xl font-bold">What is TOTC?</h2>
          <p className="mt-4 text-center text-sm text-gray-600">
            TOTC is a platform that allows educators to create online classes whereby they can share course materials
            online, manage registrations, capture and store memory, curate grade results and provide students with
            feedback all in one place.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card className="bg-white p-4">
            <img
              alt="For Instructors"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <Button className="mt-4 w-full" variant="default">
              Start a class today
            </Button>
          </Card>
          <Card className="bg-white p-4">
            <img
              alt="For Students"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <Button className="mt-4 w-full" variant="default">
              Enroll classes
            </Button>
          </Card>
        </div>
        <div className="my-12">
          <h2 className="text-center text-2xl font-bold">
            Everything you can do in a physical classroom, you can do with TOTC
          </h2>
          <p className="mt-4 text-center text-sm text-gray-600">
            TOTC`s school management software helps traditional and online schools manage scheduling, attendance,
            payments and virtual classrooms all in one secure cloud-based system.
          </p>
          <Button className="mx-auto mt-4 block" variant="default">
            Learn more
          </Button>
        </div>
        <div className="bg-white p-4">
          <img
            alt="Classroom Interaction"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "600/200",
              objectFit: "cover",
            }}
            width="600"
          />
        </div>
      </div>
    </div>
  )
}
