"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/K8o0sVr81zr
 */
import { Input } from "@/components/ui/input";

import Link from "next/link";
import Button from "@/components/ui/Button1";
import { useState } from "react";
import { Toaster,toast } from "react-hot-toast";


export function Footer() {
  
  const [email, setEmail] = useState('');

const SubmitHandler=()=>{

  toast.success("Newsletter Subscribed !!")
}

  return (
    <div className="bg-[#161b22]  max-h-full flex flex-col justify-between">
      <Toaster/>
      <header className="text-white  py-10">
        <div className="flex justify-center">
          <div className="flex items-center space-x-4">
            <HexagonIcon className="text-[#bd1e59] h-8 w-8" />
            <div>
              <h1 className="text-2xl font-bold">EduTrack</h1>
              <p className="text-sm">Empowering Eduction through Data</p>
            </div>
          </div>
        </div>
      </header>
      <main className="flex-grow">
        <div className="flex flex-col items-center justify-center space-y-6">
          <h2 className="text-white text-lg font-semibold">
            Subscribe to get our Newsletter
          </h2>
          <div className="flex flex-col md:flex-row items-center justify-center md:justify-between space-y-4 md:space-y-0 md:space-x-4">
            <Input
              className="rounded-full px-4 py-2 text-black"
              placeholder="Your Email"
              type="email"
              value={email}
            onChange={(e) => setEmail(e.target.value)}
            />
            <Button className="bg-[#8B5CF6] text-white rounded-full px-6 py-2" onClick={SubmitHandler}>
              Subscribe
            </Button>
          </div>
        </div>
      </main>
      <footer className="text-white py-6">
        <div className="flex flex-col items-center">
          <div className="flex flex-col md:flex-row items-center justify-center md:justify-between space-y-4 md:space-y-0 md:space-x-4 mb-4">
            <Link className="text-[#94A3B8] hover:text-white" href="#">
              Careers
            </Link>
            <Link className="text-[#94A3B8] hover:text-white" href="#">
              Privacy Policy
            </Link>
            <Link className="text-[#94A3B8] hover:text-white" href="#">
              Terms & Conditions
            </Link>
          </div>
          <p className="text-[#94A3B8] text-xs">
            © 2024 TOTC
          </p>
        </div>
      </footer>
    </div>
  );
}

function HexagonIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
    </svg>
  );
}
