/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tjaAb77qrVp
 */
"use client"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function LoginPages() {
  return (
    <div className="flex h-screen">
      <div
        className="w-1/2 bg-cover bg-no-repeat"
        style={{
          backgroundImage: "url('/placeholder.svg')",
        }}
      />
      <div className="w-1/2 flex flex-col justify-center px-20">
        <div className="flex justify-between mb-10">
          <Button className="bg-transparent text-blue-500 hover:bg-blue-100">Login</Button>
          <Button className="bg-blue-500 text-white hover:bg-blue-600">Register</Button>
        </div>
        <h1 className="text-4xl font-bold mb-6">E Learning</h1>
        <p className="text-gray-600 mb-10">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis, sit? Eum quasi qui assumenda saepe.
        </p>
        <form className="space-y-6">
          <div>
            <Input placeholder="Full Name" type="text" />
          </div>
          <div>
            <Input placeholder="Email address" type="email" />
          </div>
          <div>
            <Input placeholder="Password" type="password" />
          </div>
          <div>
            <Input placeholder="Confirm Password" type="password" />
          </div>
          <Button className="w-full bg-blue-500 text-white hover:bg-blue-600">Register</Button>
        </form>
      </div>
    </div>
  )
}
