/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bdk43W4vxtR
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function NewFooter() {
  return (
    <footer className="bg-[#161b22] text-white py-6">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 xl:px-0">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="flex items-center">
            <HexagonIcon className="text-[#bd1e59] h-8 w-8 mr-3" />
            <div>
              <p className="font-semibold text-lg">TOTC</p>
              <p className="text-sm">Virtual Class for Zoom</p>
            </div>
          </div>
          <div className="flex items-center justify-center md:justify-end">
            <form className="flex items-center">
              <Input className="rounded-l-md px-4 py-2 w-full md:w-auto" placeholder="Your Email" type="email" />
              <Button className="bg-[#bd1e59] text-white rounded-r-md px-6 py-2 ml-2">Subscribe</Button>
            </form>
          </div>
        </div>
        <div className="flex flex-col md:flex-row justify-between items-center mt-4 border-t border-gray-700 pt-4">
          <div className="flex space-x-4 text-sm">
            <Link className="hover:text-[#bd1e59]" href="#">
              Careers
            </Link>
            <Link className="hover:text-[#bd1e59]" href="#">
              Privacy Policy
            </Link>
            <Link className="hover:text-[#bd1e59]" href="#">
              Terms & Conditions
            </Link>
          </div>
          <div className="text-sm mt-4 md:mt-0">© 2021 Class Technologies Inc.</div>
        </div>
      </div>
    </footer>
  )
}


function HexagonIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
    </svg>
  )
}
