/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nbhcSU4f9pK
 */
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function Response() {
  return (
    <div className="bg-white p-8 rounded-lg shadow-md max-w-2xl mx-auto">
      <form className="space-y-8">
        <div>
          <div className="flex items-center space-x-2 mb-4">
            <div className="text-blue-500">1</div>
            <h2 className="text-lg font-semibold">HOW`S YOUR HEALTH?</h2>
          </div>
          <RadioGroup defaultValue="average">
            <div className="flex justify-between">
              <RadioGroupItem id="health-poor" value="poor" />
              <Label htmlFor="health-poor">Poor</Label>
              <RadioGroupItem id="health-could-be-better" value="could-be-better" />
              <Label htmlFor="health-could-be-better">Could be better</Label>
              <RadioGroupItem id="health-average" value="average" />
              <Label htmlFor="health-average">Average</Label>
              <RadioGroupItem id="health-good" value="good" />
              <Label htmlFor="health-good">Good</Label>
              <RadioGroupItem id="health-excellent" value="excellent" />
              <Label htmlFor="health-excellent">Excellent</Label>
            </div>
          </RadioGroup>
        </div>
        <div>
          <div className="flex items-center space-x-2 mb-4">
            <div className="text-blue-500">2</div>
            <h2 className="text-lg font-semibold">HOW ACTIVE ARE YOU?</h2>
          </div>
          <RadioGroup defaultValue="average">
            <div className="flex justify-between">
              <RadioGroupItem id="activity-very-inactive" value="very-inactive" />
              <Label htmlFor="activity-very-inactive">Very Inactive</Label>
              <RadioGroupItem id="activity-inactive" value="inactive" />
              <Label htmlFor="activity-inactive">Inactive</Label>
              <RadioGroupItem id="activity-average" value="average" />
              <Label htmlFor="activity-average">Average</Label>
              <RadioGroupItem id="activity-active" value="active" />
              <Label htmlFor="activity-active">Active</Label>
              <RadioGroupItem id="activity-very-active" value="very-active" />
              <Label htmlFor="activity-very-active">Very Active</Label>
            </div>
          </RadioGroup>
        </div>
        <div>
          <div className="flex items-center space-x-2 mb-4">
            <div className="text-blue-500">3</div>
            <h2 className="text-lg font-semibold">WHICH IMAGE APPLIES TO YOU</h2>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <img
              alt="Option 1"
              className="rounded-lg"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "160/120",
                objectFit: "cover",
              }}
              width="160"
            />
            <img
              alt="Option 2"
              className="rounded-lg"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "160/120",
                objectFit: "cover",
              }}
              width="160"
            />
          </div>
        </div>
        <div>
          <div className="flex items-center space-x-2 mb-4">
            <div className="text-blue-500">4</div>
            <h2 className="text-lg font-semibold">DO YOU ALWAYS FEEL TIRED?</h2>
          </div>
          <RadioGroup defaultValue="average">
            <div className="flex justify-between">
              <RadioGroupItem id="tired-always" value="always" />
              <Label htmlFor="tired-always">Always</Label>
              <RadioGroupItem id="tired-often" value="often" />
              <Label htmlFor="tired-often">Often</Label>
              <RadioGroupItem id="tired-average" value="average" />
              <Label htmlFor="tired-average">Average</Label>
              <RadioGroupItem id="tired-no" value="no" />
              <Label htmlFor="tired-no">No</Label>
              <RadioGroupItem id="tired-never" value="never" />
              <Label htmlFor="tired-never">Never</Label>
            </div>
          </RadioGroup>
        </div>
        <div>
          <div className="flex items-center space-x-2 mb-4">
            <div className="text-blue-500">5</div>
            <h2 className="text-lg font-semibold">ACTIVITIES, SELECT ALL THAT APPLY</h2>
          </div>
          <div className="grid grid-cols-3 gap-4">
            <Checkbox id="activity-yoga" />
            <Label htmlFor="activity-yoga">Yoga</Label>
            <Checkbox id="activity-cycling" />
            <Label htmlFor="activity-cycling">Cycling</Label>
            <Checkbox id="activity-dancing" />
            <Label htmlFor="activity-dancing">Dancing</Label>
            <Checkbox id="activity-dog-walks" />
            <Label htmlFor="activity-dog-walks">Dog Walks</Label>
            <Checkbox id="activity-martial-arts" />
            <Label htmlFor="activity-martial-arts">Martial Arts</Label>
          </div>
        </div>
        <div>
          <div className="flex items-center space-x-2 mb-4">
            <div className="text-blue-500">6</div>
            <h2 className="text-lg font-semibold">ANY HEART CONDITIONS IN THE FAMILY?</h2>
          </div>
          <Select>
            <SelectTrigger id="family-heart-conditions">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="yes">Yes</SelectItem>
              <SelectItem value="no">No</SelectItem>
              <SelectItem value="not-sure">Not Sure</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <div className="flex items-center space-x-2 mb-4">
            <div className="text-blue-500">7</div>
            <h2 className="text-lg font-semibold">RATE YOUR ENERGY LEVEL</h2>
          </div>
          <input className="w-full" defaultValue="50" max="100" min="0" type="range" />
        </div>
        <div className="flex justify-center">
          <Button>Submit</Button>
        </div>
      </form>
    </div>
  )
}
