/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gLlKL627QNj
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { CardContent, Card } from "@/components/ui/card"

export function studentlist1_2() {
  return (
    <div className="overflow-hidden bg-gray-100 dark:bg-gray-850">
      <div>
        <div>
          <div>Students</div>
          <div>List of enrolled students</div>
          <div>
            <Button size="sm">Add Student</Button>
          </div>
          <div>
            <SearchIcon className="h-4 w-4" />
            <Input placeholder="Search students..." type="text" />
          </div>
        </div>
        <div className="p-4 md:p-6">
          <Card>
            <CardContent className="p-4 md:p-6">
              <div className="overflow-x-auto">
                <table className="w-full border-collapse text-left table-auto">
                  <thead>
                    <tr>
                      <th className="pb-2 md:pb-4">Name</th>
                      <th className="pb-2 md:pb-4">Email</th>
                      <th className="pb-2 md:pb-4">Courses</th>
                      <th className="pb-2 md:pb-4">Status</th>
                      <th className="pb-2 md:pb-4">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-t hover:bg-gray-100 dark:hover:bg-gray-900">
                      <td className="py-3 md:py-4">Alice Johnson</td>
                      <td className="py-3 md:py-4">alice@example.com</td>
                      <td className="py-3 md:py-4">Math, Science</td>
                      <td className="py-3 md:py-4">Active</td>
                      <td className="flex items-center space-x-2 py-3 md:py-4">
                        <Button size="sm">View</Button>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="outline">
                          Remove
                        </Button>
                      </td>
                    </tr>
                    <tr className="border-t hover:bg-gray-100 dark:hover:bg-gray-900">
                      <td className="py-3 md:py-4">Bob Smith</td>
                      <td className="py-3 md:py-4">bob@example.com</td>
                      <td className="py-3 md:py-4">History, English</td>
                      <td className="py-3 md:py-4">Active</td>
                      <td className="flex items-center space-x-2 py-3 md:py-4">
                        <Button size="sm">View</Button>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="outline">
                          Remove
                        </Button>
                      </td>
                    </tr>
                    <tr className="border-t hover:bg-gray-100 dark:hover:bg-gray-900">
                      <td className="py-3 md:py-4">Eve Wilson</td>
                      <td className="py-3 md:py-4">eve@example.com</td>
                      <td className="py-3 md:py-4">Art, Music</td>
                      <td className="py-3 md:py-4">Active</td>
                      <td className="flex items-center space-x-2 py-3 md:py-4">
                        <Button size="sm">View</Button>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="outline">
                          Remove
                        </Button>
                      </td>
                    </tr>
                    <tr className="border-t hover:bg-gray-100 dark:hover:bg-gray-900">
                      <td className="py-3 md:py-4">Max Brown</td>
                      <td className="py-3 md:py-4">max@example.com</td>
                      <td className="py-3 md:py-4">Gym, Health</td>
                      <td className="py-3 md:py-4">Active</td>
                      <td className="flex items-center space-x-2 py-3 md:py-4">
                        <Button size="sm">View</Button>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="outline">
                          Remove
                        </Button>
                      </td>
                    </tr>
                    <tr className="border-t hover:bg-gray-100 dark:hover:bg-gray-900">
                      <td className="py-3 md:py-4">Lily Lee</td>
                      <td className="py-3 md:py-4">lily@example.com</td>
                      <td className="py-3 md:py-4">Dance, Drama</td>
                      <td className="py-3 md:py-4">Active</td>
                      <td className="flex items-center space-x-2 py-3 md:py-4">
                        <Button size="sm">View</Button>
                        <Button size="sm">Edit</Button>
                        <Button size="sm" variant="outline">
                          Remove
                        </Button>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}


function SearchIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
